version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo npm install
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Run Tests
          command: sudo npm test #change test in package.json 

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Deploy to Vercel
          command: vercel --token $VERCEL_TOKEN --prod --yes

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
