version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install mocha
          command: sudo npm install
      - run:
          name: Run Tests
          command: SUPABASE_URL=$SUPABASE_URL SUPABASE_KEY=$SUPABASE_KEY sudo npm test

  deploy:
    docker:
      - image: circleci/node:16
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Deploy
          command: vercel deploy --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
