version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install mocha
          command: sudo npm install
      # - run:
      #     name: Debug Tests
      #     command:  echo "SUPABASE_URL:$SUPABASE_URL"
      - run:
          name: Run Tests
          command: |
            echo "export SUPABASE_URL=$SUPABASE_URL" >> $BASH_ENV
            echo "export SUPABASE_KEY=$SUPABASE_KEY" >> $BASH_ENV
            source $BASH_ENV
            npm test

  deploy:
    docker:
      - image: circleci/node:16
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Deploy
          command: vercel deploy --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
